### ISSUE TITLE
Create mount point for test documentation

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/PaddlePaddle.org#103]
Place where Travis can deploy new documentation structure

**Comment by varunarora** [comment]
Going to temporarily assign non-mounted dir `\var\contentv2` on staging server

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/scripts/travis/deploy-image.sh

**Comment by varunarora** [comment]
Awesome, we are going to be using `/var/content_staging` instead. Closing.
