### ISSUE TITLE
Add Scripts to Deployment Process to Re-Parent Content URL

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#104]
Right now we have 'paddlepaddle.org/tutorial' that points to the book repo. We plan to make the url more straightforward like 'paddlepaddle.org/tutorial/book/01.linear_regression/index.html'.

**Comment by varunarora** [comment]
Are we still planning to re-parent content? Or have we decided against it?

**Comment by daming-lu** [comment]
No we don't do the re-parenting

**Comment by daming-lu** [comment]
We halted this idea.
