### ISSUE TITLE
Update deploy-image.sh to mount external drive to v2 

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#106]
The v2 version of content structure will be stored under a separated folder. 
The deploy-image.sh should be updated to map the /var/content to the new folder for staging/develop environment.

**Comment by varunarora** [comment]
@daming-lu What's the status of this?

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/scripts/travis/deploy-image.sh
