### ISSUE TITLE
[Discussion] Update to new folder structure

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#112]
The new content data structure should be following:
* /doc
  * /[version]
    * /tutorial
      * /getting_started
      * /application
      * /advanced
    * /documentation
      * /api
      * /models

**Comment by varunarora** [comment]
I think `getting_started` is more like `getting-started`

**Comment by jetfuel** [comment]
Update: The structure is now

* /doc
  * /[version]
    * /documentation
    * /book
    * /models
* /blog
