### ISSUE TITLE
Deploy book to new folder

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#114]
/var/contentv2/documentation/book

**Comment by varunarora** [comment]
@daming-lu Where are we on this?

**Comment by daming-lu** [comment]
https://travis-ci.org/bobateadev/book/builds/287293995

**Comment by daming-lu** [comment]
https://github.com/bobateadev/book/commit/f08eb0c4d5104882ddd40a09df545bd1a98750c7

**Comment by daming-lu** [comment]
'v0.10.0' and 'develop' on 'book' are now the 2 branches for versions. Whenever a contributor contributes to book, it will be automatically generating clean html&image, stripping off redundant styles and deploying to target VM.
