### ISSUE TITLE
Create version branch for 'models' and 'book'

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#121]

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/Add-Version-Branches-to-'book'-and-'models'-repos

**Comment by luotao1** [comment]
Currently, book and models are based on develop branch of Paddle. If you create version branch, there may exist some bugs when running the examples of book or models.

**Comment by jetfuel** [comment]
When we create the version branch for book and models, we will go back to the git history to find an appropriated git commit and use that as the head of the version branch. This should provide users with the proper documentations when they reading older versions.

**Comment by daming-lu** [comment]
https://github.com/bobateadev/book/tree/v0.10.0

https://github.com/bobateadev/models/tree/v0.10.0
