### ISSUE TITLE
Install and demo in homepage

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#123]
There are two quick Install for PaddlePaddle:
- pip: (OS: centos 7, ubuntu 16.04, macos 10.12, python: python 2.7.x)
```
pip install paddlepaddle
```
- docker:
```
docker pull paddlepaddle/paddle:latest
```

And maybe the design can follow: https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=compile

**Comment by typhoonzero** [comment]
`paddlepaddle/paddle:0.10.0` is a bit old, can add `paddlepaddle/paddle` to pull latest image.

**Comment by luotao1** [comment]
@typhoonzero Thx, `docker pull paddlepaddle/paddle:latest` is better.

**Comment by llxxxll** [comment]
Docker is still a strange software for most developers in China.

**Comment by luotao1** [comment]
As `fit_a_line` is still complex for new users. We should provide a much simpler demo in homepage. There are some chooses:
1. **print topology of layer:  the code is short, but the output is really long**
- code:
```
import paddle.v2 as paddle
x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(13))
y = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear()) 
print paddle.layer.parse_network(y)
```
- output: 
```
type: "nn"
layers {
  name: "x"
  type: "data"
  size: 13
  active_type: ""
}
layers {
  name: "__fc_layer_0__"
  type: "fc"
  size: 1
  active_type: ""
  inputs {
    input_layer_name: "x"
    input_parameter_name: "___fc_layer_0__.w0"
  }
  bias_parameter_name: "___fc_layer_0__.wbias"
}
parameters {
  name: "___fc_layer_0__.w0"
  size: 13
  initial_mean: 0.0
  initial_std: 0.277350098113
  dims: 13
  dims: 1
  initial_strategy: 0
  initial_smart: true
}
parameters {
  name: "___fc_layer_0__.wbias"
  size: 1
  initial_mean: 0.0
  initial_std: 0.0
  dims: 1
  dims: 1
  initial_strategy: 0
  initial_smart: false
}
input_layer_names: "x"
output_layer_names: "__fc_layer_0__"
sub_models {
  name: "root"
  layer_names: "x"
  layer_names: "__fc_layer_0__"
  input_layer_names: "x"
  output_layer_names: "__fc_layer_0__"
  is_recurrent_layer_group: false
  reversed: false
}
```

**Comment by huxiaoman7** [comment]
when we use pip to install paddlepaddle,the default version is cpu,if we want to install it with gpu version, we can use:

`pip install paddlepaddle-gpu`

the python package name of two version are really similar to mix up

**Comment by NHZlX** [comment]
There are too much redundant information for users when print the topology of the Network, such as 
`parameters` and `sub_models`.

**Comment by rongshunlin** [comment]
I have used the pip install paddlepaddle-gpu. After I did this,it works. But I came up with the problem of numpy. It seems that you should uninstall numpy and reinstall the paddlepaddle-gpu.

**Comment by varunarora** [comment]
@luotao1 Both printing topology of a network and printing parameters make it short, but IMHO, they don't actually help you accomplish anything using PaddlePaddle.

Do you think there is an opportunity to really simplify fitting a line? On the other hand, if you think that printing the topology or showing the shape of the parameters is a much better idea, I'll go ahead and propose it visually here.

**Comment by luotao1** [comment]
>  they don't actually help you accomplish anything using PaddlePaddle

I agree with you.

> Do you think there is an opportunity to really simplify fitting a line?

Maybe can we use the inference instead of training to show fitting a line? The inference code is much shorter than training.
```
# init
paddle.init(use_gpu=with_gpu, trainer_count=1)

# network config
x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(13))
y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())

# test_data
test_data =  paddle.dataset.uci_housing.test()[0]
with open('fit_a_line.tar', 'r') as f:  # we should provide a trained_model first
    parameters = paddle.parameters.Parameters.from_tar(f) 
   
probs = paddle.infer(
     output_layer=y_predict, parameters=parameters, input= test_data)

for i in xrange(len(probs)):
     print "predict=" + str(probs[i][0])
```

**Comment by varunarora** [comment]
@luotao1 I think that is excellent idea! Inference with a pre-trained model is also much more relatable to a new person too. Visual proposal on its way.

**Comment by varunarora** [comment]
Draft 1 below, please share feedback and improvement suggestions (you might need to open the image in a new window to properly see it):

![paddlepaddle-quickstart](https://user-images.githubusercontent.com/629203/31798546-2ece4874-b4e9-11e7-8147-3ad41dfca5bc.png)

**Comment by luotao1** [comment]
The draft is amazing!! I will upload the fit_a_line.tar into book repo, in order to run this code successfully.

**Comment by typhoonzero** [comment]
Should be: 

"Tested on CentOS 7, Ubuntu 16.04, MacOS 10.12 with Python 2.7.x"

**Comment by varunarora** [comment]
Progress in #201. Only thing missing at this stage is the proper link to `fit_a_line.tar`

**Comment by varunarora** [comment]
Resolved with the help of @luotao1 and @jetfuel.
