### ISSUE TITLE
Create 0.10.0 sitemap.json

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#127]
Create the new 0.10.0.json under sitemap folder.
The structure should follow the doc: https://docs.zoho.com/writer/open/33cu11e19ea00511e41908216590a529c032c

**Comment by jetfuel** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/pull/133

**Comment by varunarora** [comment]
Merged.
