### ISSUE TITLE
Consolidate CSS styles for book, models and documentation

### ISSUE THREAD

**Issue by cs2be** [PaddlePaddle/PaddlePaddle.org#130]
This task "Strip out styling and JS from generated doc" (https://github.com/PaddlePaddle/PaddlePaddle.org/issues/101) strips css and js from the original content repos.

This new task will be to consolidate the CSS from all 3 content repos

**Comment by varunarora** [comment]
Progress in #135

**Comment by varunarora** [comment]
Progress in #165

**Comment by varunarora** [comment]
Completed in #168
