### ISSUE TITLE
Document sitemap configuration

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/PaddlePaddle.org#131]
Write a Wiki document (https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/sitemap-configurations) on how to create and modify sitemap configurations, and how to submit them for review and integration.

**Comment by jetfuel** [comment]
Ready
https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/sitemap-configurations

**Comment by varunarora** [comment]
This is amazing, @jetfuel! Closing.
