### ISSUE TITLE
Include search index in the transformed Sphinx dir

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/PaddlePaddle.org#147]
On sphinx output strip and transform, explicitly load `searchindex.js`

**Comment by varunarora** [comment]
Only for `0.10.0` and `develop`

**Comment by varunarora** [comment]
Extending this task: We need to preserve all the `.txt` files in the untransformed dir. These are used for the JS search to generate the snippet previews.

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/commit/166be417a86d0873cfb56040cca7f049720977c1
