### ISSUE TITLE
Could we slightly rearrange the content directory in the paddlepaddle.org container?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/PaddlePaddle.org#177]
In the image https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/assets/workflow.png, it says that `book`, `models`, etc are git-cloned into `/content`.  This is slightly different from the convention used in the PaddlePaddle [builder Docker image](https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile), which clones the Paddle repo into `/paddle`.  Given that users need to provide command line flags like

```bash
docker run -v $HOME/work/paddle:/paddle paddle:dev
```

and

```bash
docker run -v $HOME/work/paddle:/content/paddle paddle:doc
```

how about we keep it consistent that both the documentation and development containers assume that the Paddle repo being cloned into `/paddle`?

**Comment by wangkuiyi** [comment]
It would be nice to keep the directory mapping consistent, but if it is technically difficult, please feel free to ignore this suggestion.

**Comment by varunarora** [comment]
@wangkuiyi You are right. But I think our diagram is a little misleading in that it doesn't explicitly explain that what goes into `/content` is the exported out. We will come up with better documentation on this very soon. Thanks for pointing this out!

**Comment by jetfuel** [comment]
I am going to close this issue. The `/content` is used for transformed content.
