### ISSUE TITLE
Make a Centralized Deployment Script to PaddlePaddle.org

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#188]
Right now each content repo (book, models, documentation) does the stripping and deploying itself. It is hard to maintain. We plan to move this process to a centralized place in PaddlePaddle.org.

**Comment by varunarora** [comment]
Progress in #187

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/pull/187/files

**Comment by daming-lu** [comment]
https://github.com/bobateadev/book/pull/4

**Comment by daming-lu** [comment]
https://github.com/bobateadev/models/pull/2
