### ISSUE TITLE
Update homepage background image

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#198]
There are two candidates for the background.

The poll can be found here: https://github.com/PaddlePaddle/Paddle/issues/5022

![screen shot 2017-10-23 at 11 23 53 am](https://user-images.githubusercontent.com/1093725/31906354-c161714e-b7e5-11e7-8ec3-69d8d888e0f5.png)
source: https://pixabay.com/photo-2151568/

![screen shot 2017-10-23 at 10 58 12 am](https://user-images.githubusercontent.com/1093725/31906356-c4817202-b7e5-11e7-980a-1cb3494fcfd5.png)
srouce: https://www.shutterstock.com/image-photo/group-man-rowing-wooden-boat-evening-504393313?src=Uu3Pav4_ZQscAZJ9LJSZjg-1-22

The current poll result: Image 1: 12, image 2: 3
Prepare the winning image with shades.

**Comment by varunarora** [comment]
Progress in #205
