### ISSUE TITLE
PaddlePaddle贡献者纪念品-周边产品定制

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/PaddlePaddle.org#223]
我们正在为PaddlePaddle的贡献者定制新一轮的周边产品，以下是目前考虑的几个方案，最终纪念品的定制会参考大家的意见。
请大家回复1、2、3做投票。
如果都接受，请点向上手势。如果都不喜欢，请点向下手势。

# 1、**创想家系列**
![1](https://user-images.githubusercontent.com/32129961/32093020-622610fe-bb2d-11e7-912e-2a637b5ef50b.png)
![2](https://user-images.githubusercontent.com/32129961/32093021-625940aa-bb2d-11e7-8d51-444a0748b7eb.png)

# 2、**自由行系列**
![1](https://user-images.githubusercontent.com/32129961/32093441-dcceb3f0-bb2e-11e7-995d-d0f57a919c34.png)
![2](https://user-images.githubusercontent.com/32129961/32093449-e27bd4b8-bb2e-11e7-9ada-84e95614d55d.png)

# 3、**校园侠系列**
![1](https://user-images.githubusercontent.com/32129961/32093476-fcbec84e-bb2e-11e7-8abf-b77bcbbdabd9.png)
![2](https://user-images.githubusercontent.com/32129961/32093582-63bdbbfe-bb2f-11e7-800a-61710578082a.png)

**请大家回复1、2、3做投票（数字对应的系列已经注明）
如果都接受，请点向上手势。如果都不喜欢，请点向下手势。**

**Comment by Xreki** [comment]
1

**Comment by luotao1** [comment]
3 有粉色的么

**Comment by shangguanyifeng** [comment]
3没有粉色

**Comment by lcy-seso** [comment]
这三种都不可爱，好沉闷。。。

**Comment by luotao1** [comment]
可不可以像T恤一样，出两款。一款是比较正式普遍点，类似黑色的T恤；一款就颜色风格活泼点，类似黄色的T恤。北极狐或者anello的双肩包颜色就很丰富。

**Comment by jetfuel** [comment]
1, 2

**Comment by jetfuel** [comment]
BTW, Is this issue in the right repository? This repo is PaddlePaddle.org, not Paddle. Most contributors might miss the opportunity to vote.
