### ISSUE TITLE
Formulas in 'book' are not rendered in the math way

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#256]
Here is staging:

![staging](https://user-images.githubusercontent.com/5635322/32394574-d087ac34-c09a-11e7-8996-46efef5176cc.png)

Here is the existing:

![existing](https://user-images.githubusercontent.com/5635322/32394586-d78caef8-c09a-11e7-864d-28394b735494.png)

**Comment by jetfuel** [comment]
When converting the content to HTML format, the following math function 
`${\{y_{i}, x_{i1}, ..., x_{id}\}}_{i=1}^{n}$` got converted to 
`${{y_{i}, x_{i1}, ..., x_{id}}}<em>{i=1}^{n}$`
And this messes up the parsing.
