### ISSUE TITLE
Displaying issue with Paddle Book Image Classification

### ISSUE THREAD

**Issue by zealoct** [PaddlePaddle/PaddlePaddle.org#268]
please check http://staging.paddlepaddle.org/docs/develop/book/03.image_classification/index.html#permalink-6-model-structure

the issue screenshot:
<img width="733" alt="machi 2017-11-09 10-52-49" src="https://user-images.githubusercontent.com/1227772/32586467-a9b898d2-c53d-11e7-875e-92a693f59b29.png">

http://book.paddlepaddle.org has no this problem.

**Comment by zealoct** [comment]
Many code blocks in this URL have display problem either: 
http://staging.paddlepaddle.org/docs/develop/book/08.machine_translation/index.html

**Comment by jetfuel** [comment]
@zealoct Thank you for reporting it. It is a great find. 

@daming-lu @cs2be The section for "python net = vgg_bn_drop(image)" should display  something like this:
![screen shot 2017-11-09 at 5 53 26 pm](https://user-images.githubusercontent.com/1093725/32639075-f4453ee4-c576-11e7-8bd0-df8e6e51f60c.png)

Not sure where went wrong

**Comment by jetfuel** [comment]
Should be fixed.
