### ISSUE TITLE
Another collapsed level on the right side permalinks

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#272]
<img width="231" alt="screen shot 2017-11-09 at 11 29 01 am" src="https://user-images.githubusercontent.com/1093725/32625576-72004ce2-c541-11e7-9118-ec38e91b5ee0.png">

Even though the right-hand permalinks helps users to jump to the desired topic, there are still many subtopics for each "layer type". Will it be possible to add a collapsed level for the subtopics?

**Comment by jetfuel** [comment]
@cs2be We might actually need to add another level of the navigation.

**Comment by cs2be** [comment]
This issue has been fixed
