### ISSUE TITLE
Remove the right side side permalinks on models and mobile

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#278]
http://staging.paddlepaddle.org/docs/develop/models/README.cn.html

Since there is only one root page for these two repos, having the right side permalinks feels kinda duplicating the code.

**Comment by jetfuel** [comment]
What do I really want?

**Comment by varunarora** [comment]
[What do you want](https://media.giphy.com/media/xT0xezz7WMIu899GU0/giphy.gif)
