### ISSUE TITLE
新版首页docker指导下没有翻译全

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/PaddlePaddle.org#283]
Now download the trained housing prices model into the ~/workspace directory, and paste this Python code in housing.py using your favorite editor
<img width="1160" alt="pppp" src="https://user-images.githubusercontent.com/4569055/32640206-6dc1e930-c602-11e7-8a00-3d95eda3d469.png">

**Comment by jetfuel** [comment]
Summary: Missing translation.

**Comment by jetfuel** [comment]
Done
