### ISSUE TITLE
中文漏翻译

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/PaddlePaddle.org#284]
1. 首页中文版“Tested on CentOS 7, Ubuntu 16.04, and MacOS 10.12, with Python 2.7.x installed”一句未翻译成中文。
2. 首页中文版点击“Docker”，相应内容有漏翻译，且“下载之後 安装 Docker 在你的电脑上”翻译非常生硬。

**Comment by jetfuel** [comment]
Summary: Missing translation.

**Comment by jetfuel** [comment]
Done
