### ISSUE TITLE
新网站在safari浏览器的排版bug

### ISSUE THREAD

**Issue by yjj19920505** [PaddlePaddle/PaddlePaddle.org#285]
http://staging.paddlepaddle.org 页面展示了丰富的算法支持，接下来是细分领域，机器视觉，自然语言处理等。
不过在mac用safari浏览器访问的时候，机器视觉这一行与介绍算法支持的「易用、高效xxx」这一行在同一行上，排版效果出现了问题，在chrome浏览器访问则没这个问题。
<img width="1206" alt="2017-11-10 10 18 01" src="https://user-images.githubusercontent.com/9584884/32639955-24f3e786-c601-11e7-8154-6b56f1f03cf4.png">

**Comment by jetfuel** [comment]
What's your Safari version? Try "force" refreshing the page with 'cmd' + R

**Comment by jetfuel** [comment]
Summary: Safari compatibility issue.

**Comment by shanyi15** [comment]
<img width="1262" alt="00eb9ae84db02a6604529115afd1b171" src="https://user-images.githubusercontent.com/35982308/35790325-bb659664-0a7c-11e8-9836-474d1779de01.PNG">
fixed
