### ISSUE TITLE
新版网站-深度学习入门-机器翻译页面下版面有问题

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/PaddlePaddle.org#287]
1、有的公式未被浏览器正确显示出来
2、“、、、”

<img width="864" alt="ppp" src="https://user-images.githubusercontent.com/4569055/32640146-cede135e-c58c-11e7-9fdf-91c85f608910.png">

**Comment by jetfuel** [comment]
Will Look into it. Thanks

**Comment by jetfuel** [comment]
Summary: Parsing issue. We should display `python code block like this` for **Book Repo**
