### ISSUE TITLE
模型库“Hsigmoid加速词向量训练”页面内容都加了删除线，不知道是本意如此还是有BUG

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/PaddlePaddle.org#288]
如图：
![image](https://user-images.githubusercontent.com/22857939/32640092-e00c2e20-c601-11e7-93d8-31c20f776e14.png)

**Comment by jetfuel** [comment]
duplicated of https://github.com/PaddlePaddle/PaddlePaddle.org/issues/279

**Comment by jetfuel** [comment]
Looking into it. Thank you

**Comment by jetfuel** [comment]
duplicated of #279
