### ISSUE TITLE
语义角色标注示例里边的超链接无效bug

### ISSUE THREAD

**Issue by yjj19920505** [PaddlePaddle/PaddlePaddle.org#289]
语义角色标注示例里边下面这段话，lstmemory是有超链接跳转的。
这里需要特别说明的是hidden_dim = 512指定了LSTM隐层向量的维度为128维，关于这一点请参考PaddlePaddle官方文档中lstmemory的说明。
它跳转的页面是http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html#lstmemory
结果是404 Not Found。

**Comment by jetfuel** [comment]
這是 Book 下內容錯誤，請在Book repo 提交 issue。謝謝。

**Comment by jetfuel** [comment]
Closing the issue. Please reopen this issue in the Book repo. 
@luotao1 There might be other broken links. We should take a note of it.
