### ISSUE TITLE
Chinese characters in some pictures at paddlepaddle.org

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/PaddlePaddle.org#29]
We should stick to using English for the English version of the site.

**Comment by varunarora** [comment]
@jetfuel Do you have any ideas on how we resolve this?

@luotao1 Without touching the visuals, is there a chance we could have the original home page designer give us the Photoshop files where we could make English versions of those graphics? Or perhaps just give us the English `.png`s?

**Comment by luotao1** [comment]
@varunarora I have the Photoshop files, but it is bigger than 10MB. So I can't upload here. How can I give it to you?

**Comment by varunarora** [comment]
@luotao1 Oh awesome. Branch this repo, and perhaps add to the root `assets` dir and commit/push? I am trying to think of solutions without needing to do 1-1 handoffs.

**Comment by jetfuel** [comment]
@varunarora Once the assets are ready, I can update the repo to support the different image under different environment.

**Comment by luotao1** [comment]
@varunarora As commit/push only support file less than 25MB, but this Photoshop file is 39MB. So I send to you directly by baidu hi.

**Comment by varunarora** [comment]
Aah! thanks a lot @luotao1.

@jetfuel: that would be awesome.

**Comment by varunarora** [comment]
Merged in #163
