### ISSUE TITLE
pip安装paddlepaddle之后，执行house.py出错：Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/PaddlePaddle.org#291]
![300c02064c169561ee810e249fadadbb](https://user-images.githubusercontent.com/3206718/32640489-82f23db0-c58e-11e7-819c-8439f5a9d381.png)

mac 环境，virtualenv paddle，
按照教程创建house.py， python house.py 出错

**Comment by NHZlX** [comment]
你的virtualenv 中python 以及pip版本是什么

**Comment by OleNet** [comment]
python version:
![image](https://user-images.githubusercontent.com/3206718/32645953-8c3901ee-c5af-11e7-81f6-d36e60d65d17.png)
pip version:
![image](https://user-images.githubusercontent.com/3206718/32645966-a1a5ecea-c5af-11e7-8c12-f37c32adb976.png)

**Comment by NHZlX** [comment]
你的机器应该装了多个python版本， 从stackoverflow 找了这个答案，可以参考一下
```
This problem may occur if the .so file from homebrew's formula links against a different python library than the interpreter you are running, see also [this thread](https://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu) and this response(http://code.activestate.com/lists/python-list/1806/).

If you have no other dependencies then running your program using the python interpreter from homebrew (which should be located in /usr/local/bin/) may solve the issue.
```

**Comment by jetfuel** [comment]
You might want to continue this issue in the Paddle repo. Thank you
