### ISSUE TITLE
About the website http://staging.paddlepaddle.org/

### ISSUE THREAD

**Issue by ThomasChen1991** [PaddlePaddle/PaddlePaddle.org#292]
1. Why not https, it's not hard to do it in Baidu.
2. There is only one blog in http://staging.paddlepaddle.org/blog/, I think if it's not ready, hide it.
By the way, in Chinese mode, the page head is not "博客" but "blog".
3. All pages' title is "PaddlePaddle - Train and deploy deep learning at scale", I think the title should change, such as "PaddlePaddle - Doc", "PaddlePaddle - Book", "PaddlePaddle - Models", "PaddlePaddle - Blog".

**Comment by jetfuel** [comment]
We will look into all of this. for number 2, please refer to #293

**Comment by jetfuel** [comment]
1. Will not use https for now, as the site doesn't take any user input at the moment. 
2 & 3 are both fixed.
