### ISSUE TITLE
Blog 页面目前比较空，是否可以将之前的gitchat 系列课程搬运过来呢？

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/PaddlePaddle.org#293]
Blog 页面目前比较空旷， http://staging.paddlepaddle.org/blog/ 。写新的内容需要投入精力和时间。

之前我们积累过一些内容，比如Gitchat 课程，版权属于我们自己，是否可以开一个系列（比如机器学习应用系列），把之前大家写作的一些东西搬运过来，作为Blog的初始内容。不知是否合适。

**Comment by luotao1** [comment]
同意，微信公众号上的很多文章，都可以挪过来。

**Comment by jetfuel** [comment]
這是 Blog 下內容錯誤，請在Blog repo 提交 issue。謝謝。

**Comment by jetfuel** [comment]
Should we also get some English contents for the Blog as well?

**Comment by jetfuel** [comment]
Closing this issue. Please re open it under Blog repo. Thank you.
