### ISSUE TITLE
About the page of `Mobile` in http://staging.paddlepaddle.org/

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/PaddlePaddle.org#294]
I found that the page of `Mobile` in `http://staging.paddlepaddle.org/` and the `README` in `https://github.com/PaddlePaddle/Mobile` are not exactly the same. Is there any delay?

**Comment by jetfuel** [comment]
The content is being deployed. Will look into it. Thank you

**Comment by jetfuel** [comment]
@daming-lu Please take a look at it. Thank you so much.

**Comment by daming-lu** [comment]
It is sync'ed now. We are asking the repo owners to turn on the Travis CI

![open_travis](https://user-images.githubusercontent.com/5635322/32684174-f7f31a74-c635-11e7-8c6d-c5be393e4cba.png)

**Comment by hedaoyuan** [comment]
@daming-lu Is this need to be done on the `travis-ci.com` website? I do not have this operation authority. @wangkuiyi can you help this?
