### ISSUE TITLE
首页book的连接和进入对应页面的描述不符

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/PaddlePaddle.org#297]
英文，导航中显示是Book，点击进入页面后，显示Deep Learning 101

中文，导航显示教程，点击进入页面后，显示深度学习入门。

**Comment by jetfuel** [comment]
目前是按造http://book.paddlepaddle.org/index.html 原有的描述
得在 Book Repo 上更新描述。
![screen shot 2017-11-09 at 7 38 42 pm](https://user-images.githubusercontent.com/1093725/32641928-a62154b4-c585-11e7-8331-f380150b65f8.png)
![screen shot 2017-11-09 at 7 38 50 pm](https://user-images.githubusercontent.com/1093725/32641931-aa4ffbf8-c585-11e7-8957-4cfb85e3923c.png)

**Comment by jetfuel** [comment]
@llxxxll 該更新嗎？ Should we update it?

**Comment by jetfuel** [comment]
Summary: Should be section title be "Deep learning 101" or just "Book"?

**Comment by llxxxll** [comment]
@jetfuel 主导航应该更新为『入门』， @luotao1 觉得如何

**Comment by luotao1** [comment]
> 主导航应该更新为『入门』

我觉得"Book"比“入门”好，“入门”这个词太通用了。 @llxxxll 

> Should be section title be "Deep learning 101" or just "Book"

如果在主导航用"Deep learning 101"，显得过长。 @jetfuel 

> 英文，导航中显示是Book，点击进入页面后，显示Deep Learning 101。中文，导航显示教程，点击进入页面后，显示深度学习入门。

是说进入页面后，把Deep Learning 101改成Book？把深度学习入门改成教程么？
原来这两者就不是对应的。

**Comment by typhoonzero** [comment]
导航和进入页面的描述不一致，感觉用户会比较疑惑，怀疑自己点错了。如果能在页面内有和导航一致的描述会比较连贯。

**Comment by shanyi15** [comment]
close due to #380
