### ISSUE TITLE
新版网站-模型库-pairwise网络示例代码有误

### ISSUE THREAD

**Issue by zouweijia** [PaddlePaddle/PaddlePaddle.org#299]
1、出错内容：新版网站(http://staging.paddlepaddle.org/) -》模型库-》基于Pairwise和Listwise的排序学习
2、页面链接：http://staging.paddlepaddle.org/docs/develop/models/ltr/README.html#permalink-5-ranknet-
3、出错代码函数：half_ranknet(name_prefix, input_dim)
4、出错代码截图：
![image](https://user-images.githubusercontent.com/25737891/32642224-c2e1cdc6-c60d-11e7-9f16-f7bf0f3a9426.png)
5、错误原因：
Pairwise中的网络结构是左右对称，通过指定相同的参数名称来共享参数，但是示例代码只指定了weight的name，未指定bias的name。会导致bias未共享，训练会得到两个bias。
6、修复方法：指定bias_attr的name，见下方代码
```
# fully connect layer
  hd1 = paddle.layer.fc(
    input=data,
    size=10,
    act=paddle.activation.Tanh(),
    param_attr=paddle.attr.Param(initial_std=0.01, name="hidden_w1"),
    bias_attr=paddle.attr.Param(name="hidden_bias"))
  # fully connected layer/ output layer
  output = paddle.layer.fc(
    input=hd1,
    size=1,
    act=paddle.activation.Linear(),
    param_attr=paddle.attr.Param(initial_std=0.01, name="output_w")
    bias_attr=paddle.attr.Param(name="output_bias"))
  return output
```

**Comment by jetfuel** [comment]
這個是 Models 內容錯誤，請在 Models repo 下提交 Issue。謝謝

**Comment by jetfuel** [comment]
Marked as invalid. Should move the issue to Models repo
