### ISSUE TITLE
移动端下，使用hi自带浏览器内核底部技术与服务优势板块没有自动扩充对齐

### ISSUE THREAD

**Issue by viviier** [PaddlePaddle/PaddlePaddle.org#302]
测试机 XiaoMi 6

这是使用hi自带百度浏览器查看网站，下底部未正常扩充：
![image](https://user-images.githubusercontent.com/13088377/32644946-63209b1e-c5aa-11e7-9bde-e3365bf18454.png)

这是自带浏览器查看网站正常：
![image](https://user-images.githubusercontent.com/13088377/32645009-aeb10f78-c5aa-11e7-9a11-db7d9b383ced.png)

**Comment by jetfuel** [comment]
Summary: When using Baidu Hi on a mobile phone, PPO can render properly on the Baidu Hi default web browser.
