### ISSUE TITLE
模型库里边的生成古诗词页面显示有问题

### ISSUE THREAD

**Issue by yjj19920505** [PaddlePaddle/PaddlePaddle.org#303]
模型库里边的生成古诗词，点击后显示TBD，并没有具体内容
<img width="1242" alt="2017-11-10 16 27 49" src="https://user-images.githubusercontent.com/9584884/32649668-df455fbe-c635-11e7-82b4-57ee4a37444c.png">

**Comment by lcy-seso** [comment]
这个是因为这个例子之前先merge了代码，一直没有更新README。最近提了PR，但还没有merge。会尽快把这个例子merge了，这一页下面就不会出现TBD。

**Comment by jetfuel** [comment]
Thanks for reporting.
