### ISSUE TITLE
FAQ右侧导航目录出现错误

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#319]
http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/model/index_cn.html
![image](https://user-images.githubusercontent.com/6836917/32765064-c187c000-c943-11e7-8e8b-dd87f2a72e4a.png)
http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html
![image](https://user-images.githubusercontent.com/6836917/32765077-d48f1e1e-c943-11e7-8f9f-dcd0d09b4bba.png)

第一个图中的1和2，第二个图中的4，均出现错误。看上去是无法正确解析含有代码格式的目录标题。

**Comment by jetfuel** [comment]
index_cn.rst file has this line
` 1. 出现 :code:`Duplicated layer name` 错误怎么办` 
看起來 Duplicated layer name 是應該以代碼的風格表示。

**Comment by shanyi15** [comment]
hi @jetfuel ，请问是否可以从网站解析方面解决这个问题？

**Comment by jetfuel** [comment]
@shanyi15 Yes, the site should parse the right permalinks properly to handle the :code markdown. 
@cs2be assign this to you.

**Comment by cs2be** [comment]
Fixed in https://github.com/PaddlePaddle/PaddlePaddle.org/pull/415
