### ISSUE TITLE
文档中，不同版本分支切换后，首页导航栏发生相应变化，与预期不符。

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/PaddlePaddle.org#337]
默认首页导航：
`文档  教程  模型库 English Github`

当在文档中点击切换版本为0.10.0 or 0.9.0 ，再跳转回首页，首页导航变为：

`文件 English Github`

**Comment by jetfuel** [comment]
@llxxxll 目前 Book, Models, Mobile, 都還沒有 `v0.10.0` 或 `v0.9.0` branch。只要在代碼庫建立這個 branch，Travis系統會自動在導航上建立對應的Link。而開發者可以在 `v0.10.0` 或 `v0.9.0` 上更新資料。

@luotao1 需要我幫你在Book創建這個 branch 嗎？

**Comment by luotao1** [comment]
Models, Mobile, 从时间节点来说沒有 v0.10.0 或 v0.9.0 branch。 @lcy-seso @hedaoyuan @xieyk 
对book来说，由于不像api变化特别大，都是一些细小的改动。如果有v0.11.0的版本，使用者是否没必要再去学v0.10.0的内容了？即从v0.11.0开始做好版本管理？

**Comment by llxxxll** [comment]
@jetfuel 能否让咱们的首页始终保持最稳定版本（当前0.10，未来有可能是0.11）的Link；绝大多数用户都是会选择我们默认的版本学习，这是主要需求；只有少部分用户会翻阅之前的版本或者尝试最新版本，这是次要需求；

**Comment by jetfuel** [comment]
@llxxxll `始终保持最稳定版本` 意思是說如果用戶選擇 0.9.0 時，我們還是應該提供 0.10.0 的 link 嗎(假設有 0.10.0) ？

**Comment by llxxxll** [comment]
@jetfuel 是的。但这样也不是最佳体验，我也委托duzhe帮咱们想想有没有更好的方案。

**Comment by jetfuel** [comment]
@llxxxll 目前還沒有建立 branch，需要我們現在建立 v0.10.0 branch 在 book, models, mobile 嗎？

**Comment by shanyi15** [comment]
close due to #381
