### ISSUE TITLE
教程中的机器翻译模块对应代码块显示异常.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/PaddlePaddle.org#338]
对应位置在 http://paddlepaddle.org/docs/develop/book/08.machine_translation/index.cn.html 中的
![image](https://user-images.githubusercontent.com/11489242/32986455-5becfda8-cc97-11e7-8929-36835b6bac1e.png)

**Comment by jetfuel** [comment]
@peterzhang2029 This is due to the formatting error in the markdown file. I created a PR for it. You can track it here. https://github.com/PaddlePaddle/book/pull/453
Thanks
