### ISSUE TITLE
LaTeX equations doesn't display in operators' documentation

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/PaddlePaddle.org#339]
I am accessing http://paddlepaddle.org/docs/develop/documentation/zh/operators.html, and I saw un-rendered LaTeX equations:

<img width="1329" alt="screen shot 2017-11-21 at 5 49 54 pm" src="https://user-images.githubusercontent.com/1548775/33105946-9e31e058-cee4-11e7-9f92-bd9c9657074c.png">

**Comment by varunarora** [comment]
Resolved with #342
