### ISSUE TITLE
Need a link to the demo video

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/PaddlePaddle.org#341]
In the /README.md, it says

> To run PaddlePaddle.org as a Document tool, please take a look of the tutorial video or follow the instructions below:

But there wasn't a link to the mentioned video there.

**Comment by varunarora** [comment]
I think it refers to these:

<img width="893" alt="screen shot 2017-11-22 at 5 04 13 pm" src="https://user-images.githubusercontent.com/629203/33155699-8a32cad6-cfa7-11e7-89d8-d3fd15552b2b.png">

**Comment by jetfuel** [comment]
Attached the video link to the text.
