### ISSUE TITLE
CTR error in number format

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#357]
In github: https://github.com/PaddlePaddle/models/tree/develop/ctr
![image](https://user-images.githubusercontent.com/6836917/33814928-a42c401e-de68-11e7-9ba8-586d118e246c.png)
But in website: http://www.paddlepaddle.org/docs/develop/models/ctr/README.html
![image](https://user-images.githubusercontent.com/6836917/33814947-c78831bc-de68-11e7-826a-ea374bd879de.png)
1,2,3,4 is missing

**Comment by jetfuel** [comment]
The HTML source shows they are **ol** and **li** tags
```
<ol>
  <li>
</ol>
```

CSS might the one that's causing this issue. Will dig a bit more

**Comment by luotao1** [comment]
Why this error is still in the website after #359 merged?

**Comment by jetfuel** [comment]
@luotao1 The change is on the develop branch. We need to release the change to prod in order for people to see on the www.paddlepaddle.org site. I will try to create a release today

You can also check out http://staging.paddlepaddle.org:82 for the changes not yet on production.

**Comment by luotao1** [comment]
I see it. Thank you very much!
