### ISSUE TITLE
Can website support markdown table

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/PaddlePaddle.org#360]
Can our website support markdown table? 
http://www.paddlepaddle.org/docs/0.11.0/documentation/en/howto/usage/cluster/cluster_train_en.html#starting-parameter-server

![image](https://user-images.githubusercontent.com/6836917/34099740-58fb9f3c-e41b-11e7-81dd-3f3aca5ab4aa.png)

**Comment by luotao1** [comment]
在MD里面用eval_rst加入表格，在网站上是能正确显示的，但直接点开MD就显示不正常
![image](https://user-images.githubusercontent.com/6836917/34434956-ff47dc64-ecc4-11e7-8943-b9858baad869.png)

**Comment by daming-lu** [comment]
http://www.paddlepaddle.org/docs/develop/documentation/en/howto/cluster/cmd_argument_en.html

我们注意到 doc 从 table 改成了 bullet。 不知道 table 的需求未来会不会很多。

**Comment by luotao1** [comment]
有table的需求还是会很多的，现在从table改成bullet，是因为table无法使用，必须用html格式。

**Comment by cs2be** [comment]
Fixed in https://github.com/PaddlePaddle/PaddlePaddle.org/pull/406
