### ISSUE TITLE
反馈一个官网中文翻译错误

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#379]
![image](https://user-images.githubusercontent.com/35982308/35604445-339670a8-067d-11e8-92ff-a069c00b5533.png)
如图所示，选择0.10.0版，显示的是“文件”，应当是“文档”，请修复，谢谢!

**Comment by luotao1** [comment]
duplicated with https://github.com/PaddlePaddle/Paddle/issues/6762

**Comment by daming-lu** [comment]
http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/getstarted/index_cn.html
