### ISSUE TITLE
Website Enhancement Project-1.1-Optimize the Chinese name of some modules and headlines

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#385]
Now, Chinese names of some modules and headlines make users confused, for example:
**Example 1**
root navigation:【教程】,it actually talks about deep learning, not paddlepaddle. Therefore, we think
【深度学习101】is more suitable.
**Example 2**
Root navigation【移动】，replaced by【移动端】, is easy for understanding.

Therefore，we change some Chinese names, which presented in the mind map on page 4 of [MRD](http://note.youdao.com/groupshare/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175 ) 

The mind map is updating, please wait...

Thank you very much!

------------------------------------------------------------------------------------------
**Project Background**
Polish documentation of PaddlePaddle, enhancing user experience
-----Enhancement Plan: 
Stage 1: https://note.youdao.com/share/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175#/
-----Enhancement Schedule: 
https://shimo.im/sheet/VnyT2IKRHjoU1a6i/6HGyl// 
-----V2 Website Enhancement:
https://shimo.im/sheet/uoMu6uOR6sE3Mj5L/DcJ7C

**Comment by jetfuel** [comment]
The subtitle in the book is called "深度学习入门". Are the title "深度学习101" and subtitle "深度学习入门" too similar? 

![screen shot 2018-02-05 at 2 21 16 pm](https://user-images.githubusercontent.com/1093725/35831805-dc08d3f6-0a7f-11e8-8c9c-5c4f947076b4.png)

**Comment by shanyi15** [comment]
talk with @jetfuel , we will change "深度学习入门" here to "深度学习101" as well

**Comment by shanyi15** [comment]
![image](https://user-images.githubusercontent.com/35982308/35839006-1e14f302-0b29-11e8-8ad5-2c5b98f923a5.png)
I draw the page in Axure

**Comment by jetfuel** [comment]
@shanyi15 I already checked in the code. You should be able to see the change after release
