### ISSUE TITLE
book.paddlepaddle.org website is down

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#386]
As shown in the figure, please check and repair, thank you very much!

![book](https://user-images.githubusercontent.com/35982308/35724025-52e6e454-0837-11e8-895d-eb63c7e93baa.PNG)

**Comment by jetfuel** [comment]
@shanyi15 I think the official entry point to the book section should be: http://www.paddlepaddle.org/docs/develop/book/01.fit_a_line/index.cn.html

**Comment by shanyi15** [comment]
Got it, thank you
