### ISSUE TITLE
Website Enhancement Project-7-Not refreshing the left navigation

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#387]
After clicking an button in the left navigation bar, then it jump to the top of the navigation bar like this:
![image](https://user-images.githubusercontent.com/35982308/35792185-c2350132-0a86-11e8-8204-5f86f250d0a8.png)
![image](https://user-images.githubusercontent.com/35982308/35792206-d7abbeca-0a86-11e8-89c7-69e2e78c92ef.png)
the problem brings inconvenience for users, so we hope that after clicking an button in the left navigation bar, the position keep still and will not jump to the top of the navigation bar.

Thank you very much!

------------------------------------------------------------------------------------------
**Project Background**
Polish documentation of PaddlePaddle, enhancing user experience
-----Enhancement Plan: 
Stage 1: https://note.youdao.com/share/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175#/
-----Enhancement Schedule: 
https://shimo.im/sheet/VnyT2IKRHjoU1a6i/6HGyl// 
-----V2 Website Enhancement:
https://shimo.im/sheet/uoMu6uOR6sE3Mj5L/DcJ7C

**Comment by cs2be** [comment]
Closed:  https://github.com/PaddlePaddle/PaddlePaddle.org/pull/398
