### ISSUE TITLE
Delete "Operators" under API menu

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#390]
Here is a issue about deleting "Operators" in API menu: https://github.com/PaddlePaddle/Paddle/issues/8177

Before we delete it from back-end, it should be removed from the front-end(website) first.

Please remove the "Operators" first, thank you!

Please note that this work doesn't have to wait for the website enhancement project, it could start now.

**Comment by cs2be** [comment]
Removed
