### ISSUE TITLE
Documentation-进阶使用-分布式训练‘s  left navigation expand to 4th level links

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#392]
The documentations have been reclassified in https://github.com/PaddlePaddle/Paddle/issues/8037 and there is a problem, please see: http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/cluster/multi_cluster/index_cn.html

![image](https://user-images.githubusercontent.com/35982308/35966776-c771066c-0cf9-11e8-8315-a96383bdeb7b.png)

It will be better if we make "在不同集群中运行" expand to 4th level links, the left navigation might be like: 
![3c5439ce1b3e4df368e99d909b37674c](https://user-images.githubusercontent.com/35982308/35967781-e390200a-0cfc-11e8-8080-dd517112ff9f.JPG)

**Comment by cs2be** [comment]
Fixed in https://github.com/PaddlePaddle/PaddlePaddle.org/pull/403
