### ISSUE TITLE
number and code show incorrectly

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#423]
Here: http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/capi/organization_of_the_inputs_cn.html

example:

1. number

![image](https://user-images.githubusercontent.com/35982308/36767508-c433675c-1c75-11e8-856c-f1a471a31492.png)

2. code

![image](https://user-images.githubusercontent.com/35982308/36767459-883332c8-1c75-11e8-8420-5b8154c4740a.png)

Thank you!

**Comment by jetfuel** [comment]
@shanyi15 The code block issue is fixed within the paddlepaddle.org. To fix the ordered-list issue, we should modify the paddle doc directly. It is much clear to add a line breaker before the list group in markdown file. The PR is here https://github.com/PaddlePaddle/Paddle/pull/8667
