### ISSUE TITLE
format problem of number

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#424]
here:
http://www.paddlepaddle.org/docs/develop/documentation/zh/dev/contribute_to_paddle_cn.html#permalink-14--

![image](https://user-images.githubusercontent.com/35982308/36771793-8aa260de-1c8d-11e8-94ce-ba70089496a7.png)

please fix it, thank you!

**Comment by luotao1** [comment]
There are a lot of number format problem now.

**Comment by jetfuel** [comment]
@shanyi15 @luotao1  To fix the ordered-list issue, we should modify the paddle doc directly. It is much clear to add a line breaker before the list group in markdown file. The PR is here PaddlePaddle/Paddle#8667
