### ISSUE TITLE
How to run in Docker container

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/PaddlePaddle.org#43]
I am trying to run the portal locally by following [this document](https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/INSTALL.md#run-docker-image).

However, I stopped at where a `SECRET_KEY=<secret_key>` is required. How can I have this  `secret_key`?

Also, `docker run` requires

```
-v <external_template_dir>:/var/content 
```

How can I have that `external_template_dir`?

Thanks!

**Comment by jetfuel** [comment]
The secret_key can be anything for local development. Any random string should let you proceed. 

For external _template_dir, the team manually sent the package to us for testing initially. The Travis CI will automatically update the contents to the staging server during development. 

We can send you a copy of the contents to unblock you right now.

**Comment by varunarora** [comment]
@wangkuiyi Has this been resolved for you? Anything you'd like us to do before we close this one?

**Comment by wangkuiyi** [comment]
The document https://github.com/PaddlePaddle/PaddlePaddle.org/blob/develop/INSTALL.md mentions 

> Note: Please contact product team (Varun, Jeff, Daming, Thuan) for the external_template_dir

This looks a temporary solution. Do we have a plan for where to put the template in the future?

Thanks!

**Comment by varunarora** [comment]
That is 100% correct.

@daming-lu Can you update this installation readme to explain how someone can build the static documentation without needing to get it from a person?

**Comment by daming-lu** [comment]
Fixed by @cs2be

**Comment by varunarora** [comment]
Actually, the notes about contacting someone directly are still in the `INSTALL.md` file, so re-opening.

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/commit/e012344b49a8660c6f523af7fc3e0df452ef51dd
