### ISSUE TITLE
Repair the indent format problem

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#435]
Example:
Original doc:
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/cmd_parameter/detail_introduction_en.md
![image](https://user-images.githubusercontent.com/35982308/36957727-65463210-2071-11e8-8779-bf7fce7bbff6.png)
PaddlePaddle.org:
http://www.paddlepaddle.org/docs/develop/documentation/en/howto/cmd_parameter/detail_introduction_en.html
![image](https://user-images.githubusercontent.com/35982308/36957733-7827e4e6-2071-11e8-9ad0-28a29dca17d3.png)

Chinese version website also has this problem

Please repair it, thank you!

**Comment by daming-lu** [comment]
It was working before:
<img width="1680" alt="screen shot 2018-03-05 at 10 27 52 pm" src="https://user-images.githubusercontent.com/5635322/36980182-8ed4eec0-20c4-11e8-8ab3-0616f37d6be6.png">

I will dig deeper to see if we changed something recently.

**Comment by daming-lu** [comment]
This is because we switched from Sphinx markdown to Python markdown 2 weeks ago in order to render tables correctly. Sphinx can render nested indents and anchors the right way, but not tables. I am discussing with my team lead for an optimized solution.

**Comment by daming-lu** [comment]
fixed: http://www.paddlepaddle.org/docs/develop/documentation/en/howto/cmd_parameter/detail_introduction_en.html
