### ISSUE TITLE
Sitemap broken after updating to /v2/

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/PaddlePaddle.org#438]
Hey, Jeffy!
I noticed that the sitemap is broken after we updated to /v2/ in Paddle. 

<img width="1660" alt="screen shot 2018-03-08 at 5 02 46 pm" src="https://user-images.githubusercontent.com/5635322/37142331-c04445c0-22f2-11e8-9ce7-51b9cbc69a40.png">

The content dir in .ppo_workspace looks like this:
<img width="615" alt="screen shot 2018-03-08 at 5 02 37 pm" src="https://user-images.githubusercontent.com/5635322/37142386-e608678c-22f2-11e8-821a-be6c98f6f93a.png">

Note PPO tries to find sitemap at : 
`Cannot resolve sitemap from /Users/ludaming/Baidu_USA_DamingLu/paddlepaddle.org/daming_ppo/content_dir/.ppo_workspace/content/docs/develop/book/site.en.json: 
`
But the version is actually 'doc_test'.

**Comment by daming-lu** [comment]
Oh, one more thing. Since I am working on [this](https://github.com/PaddlePaddle/PaddlePaddle.org/issues/410#issuecomment-370420812) bug, I found that the content in /api/ and in /documentation/ are exactly the same, which causes the bug. The API v2 doc is [here](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/api/index_en.rst). Note the API link in the prod is correct:

http://www.paddlepaddle.org/docs/develop/api/en/overview.html

**Comment by cs2be** [comment]
are you using PPO document builder?  yea we have to change the dir mapping on strip.py and sitemap_generator.py for develop branch to doc/v2/en doc/v2/cn doc/v2/api

**Comment by cs2be** [comment]
Fixed in https://github.com/PaddlePaddle/PaddlePaddle.org/pull/439
