### ISSUE TITLE
Previewing doc abnormally using PaddlePaddle.org tools

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/PaddlePaddle.org#442]
I  select PaddlePaddle Documentation（5min) and  try to build doc according to the link http://www.paddlepaddle.org/docs/develop/documentation/zh/dev/write_docs_cn.html, but it comes 
![image](https://user-images.githubusercontent.com/31875089/37205773-0648ed4e-23d1-11e8-8f24-c4cc2659b201.png)

After the building process stops, the page remains as follows:
![image](https://user-images.githubusercontent.com/31875089/37205732-da461244-23d0-11e8-88ba-a485d602b349.png)

**Comment by luotao1** [comment]
I am OK on `Paddle Documentation（5min）`, but fail on `Paddle API`
![image](https://user-images.githubusercontent.com/6836917/37206868-6171992e-23d5-11e8-8432-c33fd4a254fc.png)
I see there is a TODO in
https://github.com/PaddlePaddle/PaddlePaddle.org/blob/061f1797c00422f5ceea3ca1828a25d9f57fc1f1/portal/deploy/documentation.py#L52-L53
When will you fix this TODO? Thanks very much!

**Comment by weixing02** [comment]
same error to me
