### ISSUE TITLE
adjust drop list of version selector

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#449]
Now there is large blank space in drop list of version selector in "Documentation" and "API"，please see:
It cannot show completely at the edge of my browser (Chrome)
- Example
![do](https://user-images.githubusercontent.com/35982308/38161078-c3a2c038-34fa-11e8-8fef-a32866092636.jpg)

- Please adjust it

1. move the list slightly to the right, and just under the selector
please refer to https://github.com/PaddlePaddle/PaddlePaddle.org/issues/432 , 
2. please remove blank space of drop list menu
after we move the text to the right, there may be still some blank space on the left, please remove it

and after we do this, the drop list may look like this, here I find an example from the internet
![2](https://user-images.githubusercontent.com/35982308/38161130-9073af46-34fb-11e8-8ea1-1dca941d4752.jpg)

Thank you so much!

**Comment by cs2be** [comment]
please do shift refresh on browser, you have cached css

**Comment by cs2be** [comment]
please do a shift refresh on browser, you have cached css.

thanks,
thuan

Sent from my iPhone

On Mar 31, 2018, at 12:56 AM, Shan Yi <notifications@github.com<mailto:notifications@github.com>> wrote:


Now there is large blank space in drop list of version selector in "Documentation" and "API"，please see:
It cannot show completely at the edge of my browser (Chrome)

  *   Example
[do]<https://user-images.githubusercontent.com/35982308/38161078-c3a2c038-34fa-11e8-8fef-a32866092636.jpg>

  *   Please adjust it

  1.  move the list slightly to the right, and just under the selector
please refer to #432<https://github.com/PaddlePaddle/PaddlePaddle.org/issues/432> ,
  2.  please remove blank space of drop list menu
after we move the text to the right, there may be still some blank space on the left, please remove it

and after we do this, the drop list may look like this, here I find an example from the internet
[2]<https://user-images.githubusercontent.com/35982308/38161130-9073af46-34fb-11e8-8ea1-1dca941d4752.jpg>

Thank you so much!
