### ISSUE TITLE
PaddlePaddle's official website defaults on language 

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/PaddlePaddle.org#48]
Can PaddlePaddle differentiate users directly from IP addresses, from abroad or from China?. Then, according to the location of the user, it is decided that the English website or Chinese Web site will be displayed by default.
[https://github.com/PaddlePaddle/Paddle/issues/4304](url)

**Comment by jetfuel** [comment]
New PaddlePaddle.org will take user's locale and HTTP Accept-Language to detect the language and redirect the user to the proper language for the main page. We are still working on hooking the new system in. The redirect might not work for the sub-navigation page, but we do plan to support them all.

**Comment by shangguanyifeng** [comment]
Bravo!

**Comment by varunarora** [comment]
@jetfuel Do we have anything else we need to do on this one or can we close it?

**Comment by jetfuel** [comment]
@varunarora The default language will change according to user's locale already. I am going to close this issue.
