### ISSUE TITLE
[MLK] Add "About" on to the top navigation

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#486]
<img width="416" alt="screen shot 2018-06-14 at 1 16 17 pm" src="https://user-images.githubusercontent.com/1093725/41435950-331d365e-6fd5-11e8-8aab-9046501adb4a.png">

Add a new link on to the top Navigation. The "About" page should be static with no external links.

**Comment by varunarora** [comment]
Do we have the copy (text) info written for this page already? This is extremely extremely important to get right if we wish to get right, and should be written with the most deep understanding of Paddle's purpose for existence.
