### ISSUE TITLE
[MLK] Add "Community" on to the top navigation

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#487]
Add a new "Community(社区)" link to the **Chinese** top navigation
When clicked, take the users to here `http://ai.baidu.com/forum/topic/list/168`

---
Discussion: We can also show the "Community" link in the English version. When clicked, take the users to the github/issues page. This can give the English user a place to have their question answered.

**Comment by varunarora** [comment]
Excellent idea <3
