### ISSUE TITLE
[MLK] Add "Blog" to the top navigation

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#488]
Low priority
---

We should provide a place where the engineers can share release notes and stories. 
Need infrastructure design and UI design. We do have a [blog repo](https://github.com/PaddlePaddle/blog) here. We can start off here first.

**Comment by varunarora** [comment]
Yes, agreed this is low priority. But I think to estimate how long this will take, blog vs no blog is a lesser important criteria than figuring out what set of articles we might want to have had written at launch. The tech around this should be rather easy.

What articles might we envision for first release here?

**Comment by captainwoon** [comment]
blog模块我们这次迭代可以不用关注了
