### ISSUE TITLE
[MLK] Homepage Installation guide

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#489]
Update the homepage to have the follow section.
Note: Clicking the **?** mark should show system requirements. 
<img width="778" alt="screen shot 2018-06-14 at 1 34 18 pm" src="https://user-images.githubusercontent.com/1093725/41436816-ac8bddcc-6fd7-11e8-9d04-b432e9bcf716.png">

**Comment by jetfuel** [comment]
Note: We need to make sure that the engineering team can support the multiple versions. I don't think we have different pip package for CPU/GPU/

**Comment by jetfuel** [comment]
@captainwoon We checked the new installation guide. We all think that's great and will decrease the installation barrier.
I am afraid that we don't have sufficient pip release packages to support the "pip environment/cuda version selection"
For example, for each release verison, we should have a completed list of package to support all environment. 
```
paddlepaddle-gpu==0.12.0 | 0.12.0 built with CUDA 8.0 and cuDNN 5
paddlepaddle-gpu==0.11.0.post87 | 0.11.0 built with CUDA 8.0 and cuDNN 7
paddlepaddle-gpu==0.11.0.post8 | 0.11.0 built with CUDA 8.0 and cuDNN 5
paddlepaddle-gpu==0.11.0 | 0.11.0 built with CUDA 7.5 and cuDNN 5
```

However, for 0.13.0, we only have one pip package. How would you like us to approach this?

**Comment by jetfuel** [comment]
@captainwoon Dockers does increase the installation barrier. The funny thing is, we are encouraged by the engineering team to use Docker so we can isolate the environment. Because dockers can cover different environments and platforms. Can you check with the Beijing engineering team to see if they are ok with removing the docker from the recommended method?

**Comment by captainwoon** [comment]
@jetfuel docker的方式对于工程师和Paddle来说都是非常重要的，现在的问题在于我们已经将目标用户定位为【深度学习技术的初学者】，对于这些用户，我们希望提供一个最简单的推荐安装方式（即pip），docker方式对于大部分初学者来说，还是存在学习和使用门槛，放在首页会让用户存在更多的选择困惑，所以我们认为docker方式可以在【其他安装方式】中介绍就可以
对于这一模块的文案，大家可以在这里看到[http://wiki.baidu.com/pages/viewpage.action?pageId=501931698](url)另外，请 @shanyi15 补充一下不同计算芯片对应的执行命令
