### ISSUE TITLE
[MLK] Update the homepage with "First Deep Learning Experience"

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#490]
Create a "First Deep Learning Experience" on the homepage
<img width="777" alt="screen shot 2018-06-14 at 1 37 35 pm" src="https://user-images.githubusercontent.com/1093725/41436949-1dd72662-6fd8-11e8-9a5e-71ebb9584ae9.png">

Annotations:
Step1: Download the Housing model
Step2: Copy and paste the python code (fluid version)
Step3: Run `housing.py`
Each step should display the code and the expected result after running the code.

**Comment by jetfuel** [comment]
Note: After some thought, I am afraid this tile pattern is not the best approach to show the users how to use PaddlePaddle. Typically we will need a panel with full width to display code block. If we split the screen into three small tiles, it will give our users the feeling of clutters.  I suggest we keep our current design.

**Comment by varunarora** [comment]
Agree with @jetfuel I think the most optimal way to do this is the way we already have it..

**Comment by jetfuel** [comment]
@captainwoon I also feel that the tutorial might be too long. This will be a lot better if the there is "Hello World" tutorial. As we dig into this issue more, we start to see that the Deep Learning example is in its own realm. It is extremely difficult provide a short example. Last time we talked with @luotao1 to finalize the quick-start-quide, that was the shortest we can make. 

We believe that its essential for our users to see and "read" the code for them to feel comfortable  as their first step.

**Comment by jetfuel** [comment]
We need to update the code to use high level API.

**Comment by captainwoon** [comment]
@jetfuel first start 按照目前官网的形态提供就可以了，但是在视觉风格和排版上希望可以和新的官网风格保持统一
另外我给这个模块起了一个标题：开始你的第一个深度学习任务
大家可以参考一下
