### ISSUE TITLE
[MLK] Update the homepage with a "Model" section

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#491]
Provide a section of possible "Models" on the homepage
<img width="775" alt="screen shot 2018-06-14 at 1 43 14 pm" src="https://user-images.githubusercontent.com/1093725/41437309-e9893930-6fd8-11e8-8ec6-d02391e08fe2.png">
We don't necessary need to display 8 tiles, just the selected ones. The finalized list should be provided to us asap. 

Annotations:
Each tile should display an Icon. When clicked, take the users to the the associated documentation. 
When hover the mouse on top of the tile, the Icon should fade and display the model description.

**Comment by varunarora** [comment]
Great stuff - I could work on unique icons for each example.

I don't necessarily think the hover for description is good UX, but of course it can be done. We are the experts.

**Comment by jetfuel** [comment]
Note: We will use this design instead. targeting 5~8 different models. 

<img width="932" alt="screen shot 2018-06-15 at 2 07 41 pm" src="https://user-images.githubusercontent.com/1093725/41489628-81bf7634-70a5-11e8-9fd3-ed7d4aaad8fd.png">

**Comment by jetfuel** [comment]
@captainwoon Let's do 6 models for now?

**Comment by captainwoon** [comment]
我筛选出了6个既有中文文档也有英文文档的模型，并且写好了相关的文案，大家可以在这里看到这些内容[http://wiki.baidu.com/pages/viewpage.action?pageId=501931760](url)
