### ISSUE TITLE
[MLK] Update the homepage with a "Resource" section

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#492]
Provide a "Resource" section on the homepage. 
Each tile should display an Icon

Links:
深度学习基础知识(Deep Learning 101) -> Book
AI Studio -> `http://aistudio.baidu.com`
Visual DL -> `http://visualdl.paddlepaddle.org`
中文社区(Community) -> `http://ai.baidu.com/forum/topic/ list/168`

<img width="798" alt="screen shot 2018-06-14 at 1 54 49 pm" src="https://user-images.githubusercontent.com/1093725/41437887-873a77f6-6fda-11e8-81ca-d930e4fa1671.png">

**Comment by jetfuel** [comment]
The link of AI Studio require authentication. This is very confusing to users. Should we update the link to elsewhere?

**Comment by jetfuel** [comment]
Resources candidates:
Deep Learning Basics (深度学习基础)：A new documentation
AI studio：`aistudio.baidu.com` (Online by 07/05) 
PaddlePaddle Bootcamp(PaddlePaddle训练营)：http://ai.baidu.com/paddlepaddle   
Visual DL：https://github.com/PaddlePaddle/VisualDL

**Comment by varunarora** [comment]
What is AI Studio? And how does it relate to PaddlePaddle? Is there an English version or is this suggestion only valid for the chinese version? Same issue with Bootcamp?

I think we could try to have several of these in the Chinese version, but for English, we could exclusively dedicate the area of VDL.

**Comment by jetfuel** [comment]
深度学习教学 link ：http://ai.baidu.com/paddlepaddle/openCourses

**Comment by jetfuel** [comment]
@captainwoon 深度学习基础 is based in Chinese, and AI-Studio is most likely be in Chinese as well. That left this Resource section pretty empty in English version. @varunarora suggested, we can dedicate this section to VisualDL. What do you think?

**Comment by captainwoon** [comment]
资源部分的文案，以及链接可以在这里看到[http://wiki.baidu.com/pages/viewpage.action?pageId=501931788](url)
