### ISSUE TITLE
[MLK] Consolidate Documentations

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#493]
Consolidate the content of "Documentations", "API", "Book", "Model", and "Mobile" into one navigation panel. 

For API and Book, We need to create multiple levels of navigation links. For Mobile, and Model, we can just link to the current Mobile homepage and Model homepage. 

The first level links will be:
Documentations
API
Deep Learning 101
Models
Mobile
(使用文档、API、深度学习101、模型库、移动端)

<img width="291" alt="screen shot 2018-06-14 at 2 06 41 pm" src="https://user-images.githubusercontent.com/1093725/41438459-2e6f1f4e-6fdc-11e8-8097-59a7cd069351.png">

**Comment by jetfuel** [comment]
The first level link for Documentation seems redundant to me. Since the navigation panel is for "Documentations" already.

**Comment by varunarora** [comment]
Well I agree about condensing these all here. @jetfuel I think instead of calling the first level link "documentation", perhaps we could call split it by actual function, like "install and compile", "tutorials", "advanced", etc. and bring them on the same level as book, models, mobile, etc.

**Comment by captainwoon** [comment]
文档页的侧边栏结构可以在这里看到：[http://wiki.baidu.com/pages/viewpage.action?pageId=501931798](url)，这个链接中的内容请 @shanyi15 来做补充
