### ISSUE TITLE
[MLK] Update the homepage background section

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#495]
Update the background image
Update the title
Update the subtitle.
Clicking the "Learn More" button will take the user to the "About" page

<img width="794" alt="screen shot 2018-06-14 at 3 58 35 pm" src="https://user-images.githubusercontent.com/1093725/41442403-d3a965aa-6feb-11e8-9c91-7b9dbc4ab4f2.png">

**Comment by jetfuel** [comment]
@shanyi15 What's the new title, subtitle, and background page? Are we reusing the old ones here?

**Comment by captainwoon** [comment]
标题我会整理后回复大家，我看到了varun的ui稿，我会将现有需求整理到这个ui稿中，保证最大可能的复用

**Comment by jetfuel** [comment]
Copied from the feedback
We will use this design. 
<img width="944" alt="screen shot 2018-06-15 at 11 01 12 am" src="https://user-images.githubusercontent.com/1093725/41482759-706cc7f2-708b-11e8-884e-2c9af3530d50.png">

Titles:
中文主标题：最适合中国开发者和企业的深度学习框架
中文副标题：PaddlePaddle是一个易学、易用的开源深度学习框架，能够让开发者和企业安全、高效地实现自己的AI想法

"Learn more": link to "About"
"Get Started": Suggestion from @captainwoon: link to the installation section

**Comment by captainwoon** [comment]
"Get Started": Suggestion from @captainwoon: link to the installation section
@jetfuel 我可能之前没有表达清楚，我想说的是如果我们已经有了【安装模块】，这里可能就不再需要【get start】，对于中文页面来说，这里只需要提供【了解更多】就可以
