### ISSUE TITLE
[MLK] Update the homepage with a "Video" section

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#497]
Update the homepage with a new "Video" section

Add a new section with background, title, description and links. 
<img width="1022" alt="screen shot 2018-06-19 at 10 44 02 am" src="https://user-images.githubusercontent.com/1093725/41614569-b62a9d08-73ad-11e8-88aa-195319bf1655.png">

Ideally the section should support multiple videos. 

@varunarora If we want to support multiple images, how should we update the UI.

**Comment by captainwoon** [comment]
[http://wiki.baidu.com/pages/viewpage.action?pageId=501931779](url)
