### ISSUE TITLE
Revamp home page design

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#5]

**Comment by varunarora** [comment]
@jetfuel Are we planning to add quick start here? If so, that might be the only home page design update?

I am assigning this to you for now, until we are clear on the scope of this one.

**Comment by varunarora** [comment]
Discussion transitioned to #123.

**Comment by jetfuel** [comment]
@varunarora Yes, we do need to update the design. The discussion above will provide the content.

**Comment by varunarora** [comment]
Resolved and updated.
