### ISSUE TITLE
[BIG PR] Type Enter key in the search field will result error

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/PaddlePaddle.org#566]
In 82

Click the search field, type some search keyword. 
instead of selecting a suggested link, use `Enter key` to submit the form. 

It will result error in the search result. 

<img width="325" alt="screen shot 2018-07-16 at 10 52 55 am" src="https://user-images.githubusercontent.com/1093725/42774380-6b6ee7c6-88e6-11e8-9dd2-be07e44f4e98.png">

**Comment by varunarora** [comment]
@jetfuel Should the expected behavior just stop you from pressing enter? because there is no server side version of search anymore.

**Comment by jetfuel** [comment]
What do you think of redirecting to the first link in the search result. and nothing happen if there is no suggested link?

**Comment by varunarora** [comment]
Umm the approach with redirecting to the first link is that well the user didnt select that first link, it feels awkward to do an "im feeling lucky" when not intended. i think just making it a non-op is the best way to deal with this
