### ISSUE TITLE
Information Architecture of Documentation

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#58]
8hr

**Comment by varunarora** [comment]
I am going to create a Wiki page on this and link it here

**Comment by varunarora** [comment]
Started wiki page here: https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/Proposal-for-redo-of-information-architecture-of-paddlepaddle.org

**Comment by varunarora** [comment]
@bijit-baidu updated url to: https://github.com/PaddlePaddle/PaddlePaddle.org/wiki/Unified-Information-Architecture-Proposal

**Comment by varunarora** [comment]
Current stage of information architecture building complete.
