### ISSUE TITLE
UI of Document Pages

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#59]

**Comment by varunarora** [comment]
We are resorting to a redone nav left UI and redoing the underlying grid on the page. While most of this work has been finished, we are still tuning this until we have fully merged in the documentation contents

**Comment by varunarora** [comment]
Depends on and is related to work in #130 and #138

**Comment by varunarora** [comment]
Wrapped up / completed with #130
