### ISSUE TITLE
Fluid版本的那8个例子代码没有缩进

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddlePaddle.org#610]
下面是一个截图：
![image](https://user-images.githubusercontent.com/26297768/43884804-a84697aa-9be9-11e8-9b49-301ea892f94f.png)

还有表格问题：
![image](https://user-images.githubusercontent.com/26297768/43884826-bb94700c-9be9-11e8-824c-ac00dc3b506b.png)

还有第一个例子的链接失效：http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/quick_start/fit_a_line/README.cn.html

**Comment by jetfuel** [comment]
Thank you for the feedback. We are looking into the issues.

**Comment by shanyi15** [comment]
hi 夜雨，感谢反馈，链接失效问题已修复，代码缩进问题辛苦@skylarch跟进

**Comment by yeyupiaoling** [comment]
@shanyi15 好的，麻烦您们了。
