### ISSUE TITLE
Consolidation of navigation/mapping schema against content repos

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#70]

**Comment by varunarora** [comment]
I think we passed on doing this for now, and are going to use the similar paths - except we are still transforming the output dirs by, for example, not using `html` in `docs` and adding versioned dirs.

**Comment by varunarora** [comment]
Similar to / depends on #84

**Comment by cs2be** [comment]
Task has been completed in previous commits.  We are now auto-generating navigation for each content repo.
