### ISSUE TITLE
命令错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddlePaddle.org#737]
在1.2（fluid）文档下的Ubuntu安装：

![image](https://user-images.githubusercontent.com/26297768/49717315-ad22da00-fc91-11e8-8564-3b7054681f9a.png)

**Comment by jetfuel** [comment]
forward the issue to https://github.com/PaddlePaddle/FluidDoc/issues/478

**Comment by yeyupiaoling** [comment]
修复就好。
