### ISSUE TITLE
zh API doc in v1.1 disappear

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/PaddlePaddle.org#746]
http://paddlepaddle.org/documentation/docs/zh/1.1/beginners_guide/index.html
API doc in v1.1 disappear, we don't change something in FluidDoc, is this related to ppo repo's change？

**Comment by varunarora** [comment]
Very strange, investigating now.

**Comment by varunarora** [comment]
We have since resolved this issue offline.
