### ISSUE TITLE
Compiled with WITH_GPU, but no GPU found in runtime.

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/PaddlePaddle.org#766]
W0522 07:23:12.288138  7096 init.cc:128] Compiled with WITH_GPU, but no GPU found in runtime.

**Comment by Prokrus** [comment]
Do you solve the issue? I have same problem.

**Comment by qujinqiang** [comment]
i have same problem

**Comment by BlazarS** [comment]
I hava same problem.

**Comment by tsintian** [comment]
I have the same problem. pddle=1.5.1

**Comment by varunarora** [comment]
I think the right place to have this discussion would be in the core Paddle repository (https://github.com/PaddlePaddle/Paddle), since this problem comes from there.
